### ISSUE TITLE
Build boost with NDK r8e

### ISSUE THREAD

**Issue by cowcoa** [edubart/android-libs#1]
This script can't build boost 1.5.5 with Android NDK r8e, because the script used c++11 feature, and this feature is only available in Android NDK r9b or later version.

**Comment by edubart** [comment]
These scripts are made just to work with my setup and I use NDK r9b. I don't have any intent to make it support other NDKs.

**Comment by cowcoa** [comment]
Thanks for your reply, your script is very helpful to me, I have modified
your script, and now it can build boost with NDK r8e.
